.TH HA-CLUSTER-REMOVE 8 "2012-11-01"
.SH NAME
ha-cluster-remove \- remove a node from an existing HA cluster.
.SH SYNOPSIS
.B ha-cluster-remove
[\fB-hqy\fR]
[\fB-c\fR \fIhost\fR]
.SH DESCRIPTION
.B ha-cluster-remove
Remove the specified node from a SUSE Linux Enterprise High 
Availability cluster. The node name is a required argument.
.SH OPTIONS
.TP
.B -h
Display help message.
.TP
.B -q
Be quiet (don't describe what's happening, just do it).
.TP
.B -y
Answer "yes" to all prompts (use with caution).
.TP
.BI "-c " host
Specify IP address or hostname of cluster node which will
be removed from the cluster.
.SH FILE
In addition to removing the node from the cluster
configuration, the following files are deleted from
the node by \fBha-cluster-remove\fR:
.PP
.BI /etc/csync2/csync2.cfg
.BI /etc/csync2/key_hagroup
.RS
csync2 configuration files.
.RE
.BI /etc/corosync/corosync.conf
.RS
corosync configuration file.
.RE
.BI /etc/sysconfig/sbd
.RS
SBD fencing configuration.
.RE
.PP
.SH DIAGNOSTICS
A complete log of all actions is written to
.I /var/log/ha-cluster-bootstrap.log
.SH "SEE ALSO"
.BR crm (8),
.BR csync2 (1),
.BR corosync (8),
.BR ha-cluster-init (8),
.BR ha-cluster-join (8)
.SH AUTHOR
Xia Li <xli@suse.com>
Kristoffer Gronlund <kgronlund@suse.com>
