.TH SLEHA-JOIN 8 "2011-05-24"
.SH NAME
sleha-join \- Join a new node to an existing HA cluster.
.SH SYNOPSIS
.B sleha-join
[\fB-hqy\fR]
[\fB-c\fR \fIhost\fR]
[\fB-i\fR \fIif\fR]
[\fIstage\fR]
.SH DESCRIPTION
.B sleha-join
automates the addition of new nodes to a SUSE Linux
Enterprise High Availability cluster.  If invoked with
no arguments, it will:
.IP 1.
Retrieve SSH keys and csync2 configuration from that
node.
.IP 2.
Use csync2 to obtain other configuration files.
.IP 3.
Join the cluster.
.IP 4.
Start Hawk, so you can monitor the cluster and perform further
configuration in your web browser.
.PP
During the above you will be prompted for the IP address
or hostname of an existing cluster node.  This information
can alternately be specified via a command line argument.
.SH OPTIONS
.TP
.B -h
Display help message.
.TP
.B -q
Be quiet (don't describe what's happening, just do it).
.TP
.B -y
Answer "yes" to all prompts (use with caution).
.TP
.BI "-c " host
Specify IP address or hostname of existing cluster node.
.TP
.BI "-i " interface
Default to IP address on
.I interface
instead of eth0.
.TP
.I stage
Invoke only one stage of the cluster join.  The stage can be
any one of
.I ssh,
.I csync2
or
\fIcluster\fR.  If unspecified, each stage will be executed
in sequence.
.SH FILES
In addition to the Pacemaker CIB, the following files are
created or modified by \fBsleha-join\fR:
.PP
.I /root/.ssh/id_rsa
.I /root/.ssh/id_rsa.pub
.I /root/.ssh/authorized_keys
.RS
Default ssh key and authorized_keys file for root user.
.RE
.I /etc/csync2/csync2.cfg
.I /etc/csync2/key_hagroup
.RS
csync2 configuration files.
.RE
.I /etc/corosync/corosync.conf
.RS
corosync configuration file.
.RE
.I /etc/sysconfig/sbd
.RS
SBD fencing configuration.
.RE
.PP
.SH DIAGNOSTICS
A complete log of all actions is written to
.I /var/log/sleha-bootstrap.log
.SH "SEE ALSO"
.BR csync2 (1),
.BR corosync (8),
.BR sleha-init (8)
.SH AUTHOR
Tim Serong <tserong@novell.com>
